[CmdletBinding()]
param([string]$Profile='default-static',[string]$OutputRoot='',[string]$GameFolder='',[switch]$AllowLiveRuntime,[switch]$AllowDisposableSaveMutation,[switch]$ReadyForSysAdminSuite,[string]$SysAdminSuiteOperation='',[ValidateRange(30,1800)][int]$TimeoutSeconds=300)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
if([string]::IsNullOrWhiteSpace($OutputRoot)){$OutputRoot=Join-Path $root ('.local\tbg-e2e-runs\{0}' -f (Get-Date -Format 'yyyyMMdd-HHmmss-fff'))};$OutputRoot=[IO.Path]::GetFullPath($OutputRoot);New-Item -ItemType Directory -Force -Path $OutputRoot|Out-Null
$runnerFailurePath=Join-Path $OutputRoot 'runner-failure.json';[ordered]@{schema='tbg.e2e-runner-start.v1';generatedUtc=[DateTime]::UtcNow.ToString('o');profile=$Profile}|ConvertTo-Json|Set-Content (Join-Path $OutputRoot 'runner-start.json') -Encoding UTF8
trap{[ordered]@{schema='tbg.e2e-runner-failure.v1';generatedUtc=[DateTime]::UtcNow.ToString('o');message=$_.Exception.Message;position=$_.InvocationInfo.PositionMessage;stack=$_.ScriptStackTrace}|ConvertTo-Json -Depth 10|Set-Content $runnerFailurePath -Encoding UTF8;Write-Error $_;exit 1}
Write-Host "[START] BlacksmithGuild E2E profile '$Profile' -> $OutputRoot" -ForegroundColor Cyan
function QuoteArg([string]$Value){if($Value -notmatch '[\s"]'){return $Value};'"'+($Value -replace '(\\*)"','$1$1\"' -replace '(\\+)$','$1$1')+'"'}
function InvokeBounded([string]$FilePath,[string[]]$Arguments,[string]$WorkingDirectory,[int]$Timeout){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$FilePath;$psi.Arguments=($Arguments|ForEach-Object{QuoteArg $_})-join ' ';$psi.WorkingDirectory=$WorkingDirectory;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$out=$p.StandardOutput.ReadToEndAsync();$err=$p.StandardError.ReadToEndAsync();$timedOut=-not $p.WaitForExit($Timeout*1000);if($timedOut){& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null;$p.WaitForExit()};[pscustomobject]@{ExitCode=$(if($timedOut){124}else{$p.ExitCode});TimedOut=$timedOut;Stdout=$out.Result;Stderr=$err.Result}}
$catalog=Get-Content (Join-Path $root '.tbg\harness\e2e\profiles.json') -Raw|ConvertFrom-Json;$selected=@($catalog.profiles|Where-Object id -eq $Profile)|Select-Object -First 1;if(-not $selected){throw "Unknown profile '$Profile'."}
$git=(Get-Command git -ErrorAction Stop).Source;function GitText([string[]]$Arguments){$out=& $git -C $root @Arguments 2>&1;if($LASTEXITCODE){throw "Git preflight failed: $($out -join ' ')"};($out-join "`n").Trim()};$startStatus=GitText @('status','--porcelain=v1');$runId=Split-Path -Leaf $OutputRoot;$started=[DateTime]::UtcNow
[ordered]@{schema='tbg.e2e-run-context.v1';runId=$runId;generatedUtc=$started.ToString('o');repository='EndeavorEverlasting/BlacksmithGuild';profile=$Profile;git=[ordered]@{branch=(GitText @('branch','--show-current'));head=(GitText @('rev-parse','HEAD'));dirty=(-not [string]::IsNullOrWhiteSpace($startStatus))};authority=[ordered]@{liveRuntime=[bool]$AllowLiveRuntime;disposableSaveMutation=[bool]$AllowDisposableSaveMutation;sysAdminSuiteTandem=[bool]$ReadyForSysAdminSuite}}|ConvertTo-Json -Depth 10|Set-Content (Join-Path $OutputRoot 'run-context.json') -Encoding UTF8
$results=@();$failure=$null;$blocked=$false;$proof='contract';$order=@{'contract'=0;'harness'=1;'static test'=2;'build'=3;'launcher'=4;'command ACK'=5;'behavior observed'=6;'live runtime'=7}
function Record($Journey,$Status,$Code,$Message){$script:results += [pscustomobject]@{id=$Journey.id;status=$Status;exitCode=$Code;message=$Message;proofLevel=$Journey.proofLevel};if($Status -eq 'passed' -and $order[$Journey.proofLevel] -gt $order[$script:proof]){$script:proof=$Journey.proofLevel}}
try{foreach($id in $selected.journeyIds){$j=@($catalog.journeys|Where-Object id -eq $id)|Select-Object -First 1;if(-not $j){throw "Unknown journey '$id'."};$path=if($j.script){Join-Path $root $j.script}else{$null};Write-Host "`n=== $id ===" -ForegroundColor Cyan
 switch($j.kind){
  'python'{$python=Get-Command python -ErrorAction SilentlyContinue;if(-not $python){$python=Get-Command python3 -ErrorAction Stop};$r=InvokeBounded $python.Source @($path) $root $TimeoutSeconds;if($r.Stdout){Write-Host $r.Stdout};if($r.ExitCode){throw "$id failed: $($r.Stderr)"};Record $j passed 0 'Dependency-free E2E contracts passed.'}
  'powershell'{$journeyOut=Join-Path $OutputRoot $id;$r=InvokeBounded "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" @('-NoProfile','-ExecutionPolicy','Bypass','-File',$path,'-RepoRoot',$root,'-OutputRoot',$journeyOut) $root $TimeoutSeconds;if($r.Stdout){Write-Host $r.Stdout};if($r.ExitCode){throw "$id failed: $($r.Stderr)"};Record $j passed 0 'Windows PowerShell harness contracts passed.'}
  'skill-router'{$journeyOut=Join-Path $OutputRoot $id;$r=InvokeBounded "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" @('-NoProfile','-ExecutionPolicy','Bypass','-File',$path,'-RepoRoot',$root,'-OutputRoot',$journeyOut) $root $TimeoutSeconds;if($r.Stdout){Write-Host $r.Stdout};if($r.ExitCode){throw "$id failed: $($r.Stderr)"};Record $j passed 0 'Existing v2 skill router passed.'}
  'dotnet-debug-build'{if(-not $GameFolder -or -not(Test-Path $GameFolder -PathType Container)){$blocked=$true;Record $j blocked 30 'Valid -GameFolder required.';throw 'Local build is blocked until a real game root is supplied.'};$dotnet=(Get-Command dotnet -ErrorAction Stop).Source;$r=InvokeBounded $dotnet @('build',$path,'-c','Debug',"-p:GameFolder=$GameFolder") $root $TimeoutSeconds;if($r.ExitCode){throw "Debug build failed: $($r.Stderr)"};Record $j passed 0 'Debug build passed without Release install.'}
  'read-only-runtime'{if(-not $AllowLiveRuntime){$blocked=$true;Record $j blocked 31 'Explicit -AllowLiveRuntime required.';throw 'Read-only runtime authority was not supplied.'};$expected=Join-Path $root $j.expectedArtifact;$before=if(Test-Path $expected){(Get-Item $expected).LastWriteTimeUtc}else{[DateTime]::MinValue};$r=InvokeBounded "$env:SystemRoot\System32\cmd.exe" @('/d','/c',$path) $root $TimeoutSeconds;if($r.ExitCode){throw "Read-only status refresh failed: $($r.Stderr)"};if(-not(Test-Path $expected)){throw "Expected fresh artifact missing: $($j.expectedArtifact)"};$after=(Get-Item $expected).LastWriteTimeUtc;if($after -le $before -or $after -lt $started.AddSeconds(-2)){throw 'Expected chat packet was not refreshed by this run.'};Record $j passed 0 'Fresh read-only chat packet observed; no game behavior claimed.'}
  'workflow-specific-live-runtime'{$blocked=$true;Record $j blocked 32 'Specific live workflow contract required.';throw 'Generic harness flags cannot authorize disposable-save mutation.'}
  default{throw "Unsupported journey kind '$($j.kind)'."}
 }} }catch{$failure=$_.Exception.Message}
$status=if($failure){if($blocked){'blocked'}else{'failed'}}else{'completed'};$finalStatus=GitText @('status','--porcelain=v1');$gitUnchanged=($finalStatus -eq $startStatus);if(-not $gitUnchanged -and $status -eq 'completed'){$status='failed';$failure='Repository Git state changed during E2E execution.'}
$ceiling=if($status -eq 'completed'){"Observed through '$proof'. No higher runtime claim is made."}else{'No higher than the last passed journey; review the blocker/failure.'};$artifacts=@(@{type='run-context';path='run-context.json'},@{type='artifact-registry';path='artifact-registry.json'},@{type='e2e-result';path='result.json'},@{type='operator-report';path='operator-report.md'},@{type='sprint-capsule';path='sprint-capsule.json'})
$result=[ordered]@{schema='tbg.e2e-result.v1';runId=$runId;profile=$Profile;status=$status;proofLevel=$proof;proofCeiling=$ceiling;journeys=@($results);artifacts=$artifacts;finalGit=[ordered]@{unchanged=$gitUnchanged;status=$finalStatus}};$result|ConvertTo-Json -Depth 20|Set-Content (Join-Path $OutputRoot 'result.json') -Encoding UTF8;[ordered]@{schema='tbg.e2e-artifact-registry.v1';runId=$runId;artifacts=$artifacts}|ConvertTo-Json -Depth 10|Set-Content (Join-Path $OutputRoot 'artifact-registry.json') -Encoding UTF8
@('# BlacksmithGuild E2E Result','',"- Profile: $Profile","- Status: $status","- Proof: $proof","- Ceiling: $ceiling","- Failure/blocker: $(if($failure){$failure}else{'none'})",'','## Journeys')+@($results|ForEach-Object{"- [$($_.status)] $($_.id): $($_.message)"})|Set-Content (Join-Path $OutputRoot 'operator-report.md') -Encoding UTF8
& (Join-Path $root 'scripts\tbg\New-TbgSprintCapsule.ps1') -SprintId "e2e-$runId" -Title "BlacksmithGuild E2E $Profile" -Lane 'harness-maturity' -Mission 'Run a repository-owned composed E2E profile.' -Completed @($results|Where-Object status -eq passed|ForEach-Object id) -Remaining @($results|Where-Object status -ne passed|ForEach-Object id) -Blockers $(if($failure){@($failure)}else{@()}) -Validation @("Invoke-TbgEndToEndValidation.ps1 -Profile $Profile") -ProofLevel $proof -ProofCeiling $ceiling -ClaimsNotMade @('install','launcher','command ACK','behavior observed','live runtime') -ArtifactRefs @($artifacts|ForEach-Object path) -NextCommand 'git status --short' -OutputPath (Join-Path $OutputRoot 'sprint-capsule.json') -LatestPath $(if($env:CI){''}else{'artifacts/latest/tbg-sprint-capsule.json'}) -ReadyForSysAdminSuite:$ReadyForSysAdminSuite -SysAdminSuiteOperation $SysAdminSuiteOperation|Out-Null
Write-Host "Result: $(Join-Path $OutputRoot 'result.json')" -ForegroundColor Cyan;if($status -eq 'completed'){exit 0};if($status -eq 'blocked'){exit 30};exit 1
